Added colors

diff --git a/server/tests/run b/server/tests/run
--- a/server/tests/run
+++ b/server/tests/run
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 
 dir=$(dirname "$0")
+normal="$(tput sgr0)"
+red="$(tput bold)$(tput setaf 1)"
+green="$(tput bold)$(tput setaf 2)"
 
 if lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null ; then
     for file in $(ls $dir/*.json); do
@@ -8,10 +11,10 @@ if lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null ; then
             -X POST "http://127.0.0.1:5000/screen-video" \
             -H "Content-Type: application/json" \
             -d @$file)
-        result=$(test $response = $(cat $file.expected) && echo "Passed" \
-            || echo "Failed")
+        result=$(test $response = $(cat $file.expected) \
+            && echo "${green}Passed${normal}" || echo "${green}Failed${normal}")
         printf "%-40s%s\n" $file $result
     done
 else
-    echo "Server Not Running" 1>&2
+    echo "${red}Server Not Running${normal}" 1>&2
 fi
